### ISSUE TITLE
Export zoscanovaných dát

### ISSUE THREAD

**Issue by krivy5** [TIS2024-FMFI/realsense-demo#14]
Exportovať dáta zoscanovanej miestnosti / položky, zistiť v akom formáte SDK exportuje.

**Comment by krivy5** [comment]
RealSense viewer po zaznamenaní ukladá dáta do formátu .bag (ROS bag format).

**Comment by pavelpetrovic** [comment]
do ros  bagu to uklada ROS, ale to je myslim iba zaznam sprav,  ktore sa posielaju medzi modulmi.
pre zaznam 3D modelu asi chcete pouzit nieco ine...
podla mna ROS vobec nepotrebujete pouzivat.

**Comment by krivy5** [comment]
kamera dokaze exportovat .ply files a budeme pouzivat aj streaming dat
