### ISSUE TITLE
Vytváranie aplikácie v OS Windows (prieskum)

### ISSUE THREAD

**Issue by krivy5** [TIS2024-FMFI/realsense-demo#18]
Zistiť ako sa vytvárajú aplikácie v OS Windows aké knižnice sa na to používajú čo je najvhodnejšie použiť atď.

**Comment by filip-20** [comment]
medzi najpouzivanejsie kniznice na tvorbu UI patri [DPG](https://dearpygui.readthedocs.io/en/latest/index.html), skusime ci je mozne tam integrovat nasu kameru

**Comment by spakova19** [comment]
nakoniec sme sa rozhodli použiť na tvorbu UI priamo [open3d GUI](https://www.open3d.org/html/python_api/open3d.visualization.gui.html) - bolo to pre nás najvýhodnejšie, keďže knižnicu využívame aj na vizualizáciu samotných dát
