### ISSUE TITLE
Linka ku katalógu požiadaviek

### ISSUE THREAD

**Issue by BIG-Viljo** [TIS2024-FMFI/realsense-demo#2]
V koreni repozitára treba vytvoriť dokument obsahujúci katalóg požiadaviek, ktorý bude postupne rásť a upresňovať sa.

**Comment by pavelpetrovic** [comment]
Aj v tomto pripade je ovela lepsie urobit zdielany google document.
Na Github nahrajte az hotovu verziu, ktora bude schvalena najskor cviciacim a potom zadavatelom.
Na google drive mozete vsetci opravovat chyby a dokument priebezne vylepsovat.

**Comment by BIG-Viljo** [comment]
Rovnaká otázka ako tu: https://github.com/TIS2024-FMFI/realsense-demo/issues/1#issuecomment-2395509466

**Comment by BIG-Viljo** [comment]
Neskôr sa v tomto vlákne objaví linka ku katalógu požiadaviek.

**Comment by BIG-Viljo** [comment]
[Linka ku katalógu požiadaviek](https://liveuniba-my.sharepoint.com/:w:/g/personal/hrcka14_uniba_sk/EarSqnLu2iNMi1wMwB0toioBoE90UIjrxghiLFTaCKFL3A?e=AnR56W)
