### ISSUE TITLE
Prieskum 3D knižníc v Pythone

### ISSUE THREAD

**Issue by krivy5** [TIS2024-FMFI/realsense-demo#21]
Urobiť prieskum 3D knižníc v Pythone, zistiť aké rôzne funkcie, ktoré nám dokážu pomôcť (napr. práca s meraním v 3D priestore) majú.

**Comment by filip-20** [comment]
Pre naše potreby bude najvhodnejšia knižnica [open3d](https://www.open3d.org/docs/latest/introduction.html). Pomocou nej vieme jednoducho pracovať s pointcloudom a urobiť aj GUI k našej aplikacii
