### ISSUE TITLE
Tvorba makety pre aplikáciu

### ISSUE THREAD

**Issue by krivy5** [TIS2024-FMFI/realsense-demo#22]
Vytvoriť maketu pre aplikáciu, ako bude vyzerať, ako bude rozdelená. Približné zobrazenia a možnosti aplikácie.

**Comment by spakova19** [comment]
základné mockupy vytvorené
![mockup4](https://github.com/user-attachments/assets/eb1bcb2c-8ba5-49f3-9f4e-80440110ba2a)
![mockup3](https://github.com/user-attachments/assets/e3ce94e3-19ca-4208-af2a-afad42c9bef7)
![mockup2](https://github.com/user-attachments/assets/53e29977-d8cd-4526-b846-e85f9b3dfcb2)
![mockup1](https://github.com/user-attachments/assets/af2403ab-bcff-4db5-aaf2-80478201e899)
