### ISSUE TITLE
Preskúmať gyroskop v kamere

### ISSUE THREAD

**Issue by krivy5** [TIS2024-FMFI/realsense-demo#23]
Kamera by mala obsahovať gyroskop (Inertial Measurement Unit - IMU) - pozrieť a zistiť či a ako sa dajú získať dáta z tohto gyroskopu (poprípade ako by sa dali použiť pri vytvorení 3D modela miestnosti) - všetky pre nás podstatné informácie.

**Comment by spakova19** [comment]
duplicitný issue, spájanie riešené tuto: [#20](https://github.com/TIS2024-FMFI/realsense-demo/issues/20)
