### ISSUE TITLE
Šablóna katalógu požiadaviek

### ISSUE THREAD

**Issue by BIG-Viljo** [TIS2024-FMFI/realsense-demo#3]
Pridanie základných prvkov do zdieľaného dokumentu pre katalóg požiadaviek ako sú úvodná strana, obsah a nadpisy kapitol. Tieto prvky sa môžu v budúcnosti zmeniť a telá kapitol pribudnú neskôr.

**Comment by BIG-Viljo** [comment]
Bola vytvorená základná kostra dokumentu. Zatvorte tento issue ak nemáte výhrady.

**Comment by spakova19** [comment]
formát/šablóna je v poriadku, zatváram issue
