### ISSUE TITLE
Opraviť farby pri skenovaní

### ISSUE THREAD

**Issue by filip-20** [TIS2024-FMFI/realsense-demo#32]
Farby, ktoré sa naskenujú nezodpovedajú reálnym farbám - treba skontrolovať a opraviť kód v [realsense_recorder.py](https://github.com/TIS2024-FMFI/realsense-demo/blob/main/sensors/realsense_recorder.py)

**Comment by spakova19** [comment]
farby boli opravené a vytvorený pull request bol v poriadku, zatváram issue
