### ISSUE TITLE
Vytvorenie katalógu požiadaviek

### ISSUE THREAD

**Issue by spakova19** [TIS2024-FMFI/realsense-demo#5]
Tu budú riešené všetky pripomienky a veci s katalógom požiadaviek, zároveň tu pribudne rozdelenie častí na spísanie pre konkrétnych členov

**Comment by krivy5** [comment]
Rozdelenie častí na spísanie katalógu požiadaviek:

1.1 - Noro
1.2 - Jožo
1.3 - spolu
1.4 - spolu
1.5 - Vika
2.1 - Noro
2.2 - Jožo
2.3 - Vika
2.4 - Vilo
3.  - spolu
4.  - spolu

**Comment by spakova19** [comment]
Katalóg schválený zadávateľom
