### ISSUE TITLE
Získavanie doplňujúcich informácií od zadávateľa 

### ISSUE THREAD

**Issue by krivy5** [TIS2024-FMFI/realsense-demo#6]
Mailom, popr. stretnutím, získať dopĺňujúce informácie od zadávateľa ohľadom informačného systému, ktoré neboli zadané alebo boli zadané nejasne.

**Comment by spakova19** [comment]
zaslaný mail zadávateľovi ohľadom aplikácie, keďže nebol jasne definovaný jej cieľ a taktiež požiadavky na ňu, po odpovedi od zadávateľa tu bude odpoveď priložená

**Comment by spakova19** [comment]
1. Web vs Windows aplikácia

Web aplikácia: Jednoduchšia na nasadenie zároveň je multiplatformová. Problém môže nastať 3D renderovaní pointcloudov, keďže výkon prehliadača môže byť nedostatočný.
Windows aplikácia: Má lepší prístup k hardwaru, čo eliminuje výkonové obmedzenia. Lepšie spracovanie veľkých 3D dát.
Za mňa Windows aplikácia: pre vyšší výkon, lepšiu prácu s veľkými dátami, asi aj lepšia podpora SDK
2. Upresnenie požiadaviek (predpokladám, že katalóg bude v angličtine)

Základné

Real-time Depth Stream Display: Umožniť zobrazenie hĺbkových dát v reálnom čase pri snímaní pomocou kamery, súčasne so zobrazovaním 3D pointcloudu.
Adjustable Resolution Settings: Implementovať možnosť výberu rozlíšenia a presnosti pointcloudu. Umožní rýchlejšie skenovanie pre náhľad (preview) alebo optimalizácia pre pomalšie PC.
Color Mapping of Depth Data: Integrovať RGB výstupy z kamery na vytváranie aj farebných pointcloudov.
User Interface for Measurement: Vytvoriť interaktívny nástroj, kde užívateľ môže kliknutím na dva body v 3D priestore vypočítať vzdialenosti (euklidovská)
Voliteľné – asi sa nestihne v rámci zadania predmetu

Point Cloud Cropping Tool: Umožniť používateľom vybrať oblasť v pointcloude a orezať ju, aby sa mohli zamerať na konkrétnu časť skenu.
Save/Load Scene Configuration: Umožniť používateľom uložiť a znova načítať stav scény, vrátane polohy virtuálnej kamery a všetkých údajov o meraniach.
3. STL vs PLY vs OBJ

Okrem STL je možné použiť aj iné formáty, napr. PLY alebo OBJ podľa toho na čo nájdu študenti lepšiu podporu, resp. čo bude jednoduchšie.
Môžu použiť ascii alebo binárny formát, podľa toho čo im bude viac vyhovovať
